name: Release

on:
  push:
    tags:
      - "v*"

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  AUTOLOG_URI: ${{ secrets.AUTOLOG_URI }}
  MONGODB_DB: ${{ secrets.MONGODB_DB }}
  EXPIRE_TIME_SECONDS: ${{ secrets.EXPIRE_TIME_SECONDS }}
  MONGODB_COLLECTION: ${{ secrets.MONGODB_COLLECTION }}
  TEST_MODE: false

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build the release
        run: cargo build --release

      - name: Create tarball
        run: |
          cd target/release
          tar -czf autolog-mac.tar.gz autolog

      - name: Generate SHA256
        id: sha256
        run: echo "::set-output name=sha256::$(shasum -a 256 target/release/autolog-mac.tar.gz | awk '{print $1}')"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/autolog-mac.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Homebrew Formula
        run: |
          git clone https://github.com/daveymoores/homebrew-autolog
          cd homebrew-autolog
          git checkout -b "update-formula-${GITHUB_REF#refs/tags/}"
          sed -i "s|url \".*\"|url \"https://github.com/daveymoores/autolog/releases/download/${GITHUB_REF#refs/tags/}/autolog-mac.tar.gz\"|" Formula/autolog.rb
          sed -i "s|sha256 \".*\"|sha256 \"${{ steps.sha256.outputs.sha256 }}\"|" Formula/autolog.rb
          git add Formula/autolog.rb
          git commit -m "chore: Update autolog formula to ${GITHUB_REF#refs/tags/}"
          git push origin "update-formula-${GITHUB_REF#refs/tags/}"
          gh pr create --title "Update autolog formula to ${GITHUB_REF#refs/tags/}" --body "This PR updates the autolog formula to version ${GITHUB_REF#refs/tags/}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
