name: Release

on:
  push:
    tags:
      - "v*"

env:
  AUTOLOG_URI: ${{ secrets.AUTOLOG_URI }}
  MONGODB_DB: ${{ secrets.MONGODB_DB }}
  EXPIRE_TIME_SECONDS: ${{ secrets.EXPIRE_TIME_SECONDS }}
  MONGODB_COLLECTION: ${{ secrets.MONGODB_COLLECTION }}
  API_ROUTE_BEARER_KEY: ${{ secrets.API_ROUTE_BEARER_KEY }}
  API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
  TEST_MODE: false

jobs:
  release:
    runs-on: macos-latest # Build only on macOS runner for macOS compatibility

    # Add permissions for the GITHUB_TOKEN
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Updated to latest version

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build the release
        run: cargo build --release

      - name: Set executable permission
        run: chmod +x target/release/autolog

      - name: Create tarball
        run: |
          cd target/release
          # Preserve permissions with the 'p' flag
          tar -czpf autolog-mac.tar.gz autolog

      - name: Generate SHA256
        id: sha256
        run: echo "sha256=$(shasum -a 256 target/release/autolog-mac.tar.gz | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/autolog-mac.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up GitHub CLI
        run: brew install gh # Use brew instead of apt-get on macOS

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Check if token is available
        run: |
          if [ -z "${{ secrets.AUTOLOG_ACTION_PAT }}" ]; then
            echo "Error: AUTOLOG_ACTION_PAT secret is not available"
            exit 1
          else
            echo "Secret is available"
          fi

      - name: Update Homebrew Formula
        run: |
          # Export token to an environment variable instead of using in URL
          export TOKEN="${{ secrets.AUTOLOG_ACTION_PAT }}"

          # Clone using token
          echo "Cloning repository..."
          git clone "https://${TOKEN}@github.com/daveymoores/homebrew-autolog.git"

          cd homebrew-autolog
          git checkout -b "update-formula-${GITHUB_REF#refs/tags/}" || exit 1

          echo "Updating formula..."
          # On macOS sed is different, use this syntax
          sed -i '' "s|url \".*\"|url \"https://github.com/daveymoores/autolog/releases/download/${GITHUB_REF#refs/tags/}/autolog-mac.tar.gz\"|" Formula/autolog.rb
          sed -i '' "s|sha256 \".*\"|sha256 \"${{ steps.sha256.outputs.sha256 }}\"|" Formula/autolog.rb

          git add Formula/autolog.rb
          git commit -m "chore: Update autolog formula to ${GITHUB_REF#refs/tags/}" || exit 1

          echo "Pushing changes..."
          # Push using token variable instead of hardcoding in URL
          git push "https://${TOKEN}@github.com/daveymoores/homebrew-autolog.git" "update-formula-${GITHUB_REF#refs/tags/}" || exit 1

      - name: Create Pull Request
        run: |
          cd homebrew-autolog

          # Set GH_TOKEN environment variable for GitHub CLI
          export GH_TOKEN="${{ secrets.AUTOLOG_ACTION_PAT }}"

          # Create PR with explicit head branch
          echo "Creating pull request..."
          gh pr create --head "update-formula-${GITHUB_REF#refs/tags/}" --base main --title "Update autolog formula to ${GITHUB_REF#refs/tags/}" --body "This PR updates the autolog formula to version ${GITHUB_REF#refs/tags/}" || exit 1
